version: '3.8'

services:
  messageservice:
    image: messageservice:latest
    container_name: MESSAGESERVICE
    hostname: messageservice
    build:
      context: MessageService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EUREKA__CLIENT__SERVICEURL__DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
      - mongo
      - eurekaserver
      - ocelot
    networks:
      - messagenetwork

  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - messagenetwork

  websiteservice:
    image: websiteservice:latest
    container_name: websiteservice
    build:
      context: WebsiteService
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      EUREKA__CLIENT__SERVICEURL__DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
      - messageservice
      - userservice
      - eurekaserver
      - ocelot
    networks:
      - messagenetwork

  userservice:
    image: userservice:latest
    container_name: USERSERVICE
    hostname: userservice
    build:
      context: UserService
      dockerfile: Dockerfile
    ports:
      - "5162:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EUREKA__CLIENT__SERVICEURL__DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
      - mongo
      - eurekaserver
      - ocelot
    networks:
      - messagenetwork

  eurekaserver:
    container_name: eurekaserver
    image: steeltoeoss/eureka-server:latest
    restart: always
    hostname: eurekaserver
    ports:
      - 8761:8761
    networks:
      - messagenetwork

  ocelot:
    container_name: ocelot
    build: ./apigateway-ocelot-dotnet8
    image: ocelotgatewayapi:1
    hostname: ocelot
    ports:
      - 5041:8080
    networks:
      - messagenetwork
    depends_on:
      - eurekaserver
    environment:
      EUREKA__CLIENT__SERVICEURL__DEFAULTZONE: http://eurekaserver:8761/eureka/

networks:
  messagenetwork:
    driver: bridge
