version: '3.8'

services:
  messageservice:
    image: messageservice:latest
    hostname: MESSAGESERVICE
    build:
      context: MessageService
      dockerfile: Dockerfile
    ports:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EUREKA__CLIENT__SERVICEURL__DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
      - mongo
      - eurekaserver
      - Ocelot
    networks:
      - messagenetwork
    deploy:
      mode: replicated
      replicas: 3

  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - messagenetwork

  websiteservice:
    image: websiteservice:latest
    container_name: websiteservice
    build:
      context: WebsiteService
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  userservice:
    image: userservice:latest
    hostname: USERSERVICE
    build:
      context: UserService
      dockerfile: Dockerfile
    ports:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EUREKA__CLIENT__SERVICEURL__DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
     - mongo
     - eurekaserver
     - Ocelot
    networks:
      - messagenetwork
    deploy:
      mode: replicated
      replicas: 3

  eurekaserver:
    container_name: eurekaserver
    image: steeltoeoss/eureka-server:latest
    restart: always
    hostname: eurekaserver
    ports:
      - 8761:8761
    networks:
      - messagenetwork

  Ocelot:
    container_name: Ocelot
    build: ./apigateway-ocelot-dotnet8
    image: ocelotgatewayapi:1
    hostname: Ocelot
    ports:
      - 5041:8080
    networks:
      - messagenetwork
    depends_on:
      - eurekaserver
    environment:
      EUREKA__CLIENT__SERVICEURL__DEFAULTZONE: http://eurekaserver:8761/eureka/

networks:
  messagenetwork:
    driver: bridge
